import type { Metadata } from 'next'
import localFont from 'next/font/local'
import '@/app/shared/styles/globals.css'
import MultiBrand from '../widgets/Multi-brand/Multi-brand'


const involve = localFont({
    src: '../shared/fonts/Involve-VF.ttf',
    variable: '--font-involve',
    weight: '100 900'
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en'>
            <body className={`${involve.variable}`}>{children}</body>
        </html>
    )
}
